Homework #12 Advanced topics
Alexander6463/Homework_epam pull request #15
Opened 2021-06-13 09:46 UTC by Alexander6463

- add task01, task02 and test files

2021-06-16 18:09 UTC, nikitosboroda requested changes

2021-06-16 18:09 UTC, nikitosboroda commented on homework12/hw/task02.py
> +    def set_strategy(self, strategy):
why do you need this method?

2021-06-17 06:47 UTC, Alexander6463 commented on homework12/hw/task02.py
> +    def set_strategy(self, strategy):
we can use this method, if we want to change our strategy after init object

2021-06-18 17:46 UTC, nikitosboroda approved these changes

2021-06-18 17:47 UTC, merged